name: Deploy Laravel to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:



jobs:
  test:
    name: Run Laravel Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: enjoy_report_test
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, dom, fileinfo, mysql, gd, bcmath
        coverage: none

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Setup Laravel environment
      run: |
        cp .env.example .env.testing
        php artisan key:generate --env=testing

    - name: Create testing database
      run: |
        echo "DB_CONNECTION=mysql" >> .env.testing
        echo "DB_HOST=127.0.0.1" >> .env.testing
        echo "DB_PORT=3306" >> .env.testing
        echo "DB_DATABASE=enjoy_report_test" >> .env.testing
        echo "DB_USERNAME=root" >> .env.testing
        echo "DB_PASSWORD=password" >> .env.testing

    - name: Run database migrations
      run: php artisan migrate --env=testing --force

    - name: Run tests
      run: php artisan test

  deploy:
    environment: connect_nginx
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: test  # 只有测试通过才会部署
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # 只在推送到主分支时部署

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: "azureuser"
        key: ${{ secrets.KEY }}
        port: '22'
        script: |
          # 进入项目目录
          sudo cd /www/wwwroot/kairui.engineer

          # 拉取最新代码
          sudo git pull origin main

          # 安装/更新依赖
          sudo composer install --optimize-autoloader --no-dev

          # 运行数据库迁移
          sudo php artisan migrate --force

          # 清除缓存
          sudo php artisan config:cache
          sudo php artisan route:cache
          sudo php artisan view:cache
