name: Deploy to Production Server

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug & Deploy via SSH
      uses: appleboy/ssh-action@v1
      with:
        debug: true
        host:        ${{ secrets.HOST }}
        username:    ${{ secrets.USERNAME }}
        key:         ${{ secrets.SSH_PRIVATE_KEY }}
        # passphrase:  ${{ secrets.SSH_PASSPHRASE }}   # if needed
        port:        ${{ secrets.PORT }}
        strict:      false                           # skip host-key checks
        script: |
          cd /www/wwwroot/enjoy-report.ispro.software
          git config --global --add safe.directory /www/wwwroot/enjoy-report.ispro.software
          git pull origin prod
          composer install --optimize-autoloader --no-dev --no-interaction
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
