name: Deploy to SSH Server

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to SSH Server
      uses: SamKirkland/SSH-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.SSH_SERVER }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        protocol: sftp
        port: 22
        local-dir: ./
        server-dir: ${{ secrets.SERVER_DIR }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env
          **/README.md
          **/.github/**
          **/storage/logs/**
          **/bootstrap/cache/**
          **/tests/**
          
    - name: Set permissions and run Laravel commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_SERVER }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd ${{ secrets.SERVER_DIR }}
          composer install --no-dev --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan migrate --force
          chmod -R 755 storage
          chmod -R 755 bootstrap/cache

